### ISSUE TITLE
Adding react-router dependency

### ISSUE THREAD

**Issue by gabac** [christianalfoni/webpack-example#1]
I know it's just supposed to be an example, but I found no better place, because my webpack config is based on your workflow example. Thank you very much for it!

Now to my issue:
If you try yo add react-router as a dependency. You will get in to trouble as it expects React on the window object. You end up with the following error message:
`undefined is not an object (evaluating 'React.createClass')`

I tried shimming methods for example with the imports-loader:
`require("imports?React=react!react-router")`

or add it with the ProviderPlugin

`new webpack.ProvidePlugin({
    React: "react",
    "windows.React": "react"
})`

Both didn't helped. So I did the stupid thing with `window.React = React` within my code and that worked. 

This fix works within the the dev-server. As soon as you do a build of the bundles you end up with the same error message. 

Do you have any ideas?

**Comment by christianalfoni** [comment]
Hi there,

I suppose you are loading the minified versions for fast rebundling? It is possible to fix this by bringing in the expose loader. It just makes required modules available on the gllobal scope:

In your webpack.config.js

```
module: {
  loaders: [{
      test: path.resolve(node_modules_dir, 'react/dist/react.min.js'),
      loader: "expose?React"
    }]
}
```

You basically just point to the minified file and expose it as "React" :-)

**Comment by gabac** [comment]
Good morning,

Yes that was the intention. 

Your solution worked perfectly, thanks a lot!
